name: GitHub - Activity - Readme

on:
  schedule:
    # Runs every day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme-with-github-stats:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
